language: python
python:
  - "3.8.5"
install:
  - pip install coveralls poetry
  - poetry install
branches:
  only:
    - master
    - /^v\d+\.\d+\.\d+$/
script:
  - make test
after_success:
  - coveralls
